var narodne = [
	["Aca Ilić", "Isplači se na grudima mojim"],
	["Aca Lukas", "Bele ruže"],
	["Aca Lukas", "Crni gavran"],
	["Aca Lukas", "Kafana na Balkanu"],
	["Aca Lukas", "Lična karta"],
	["Aca Lukas", "Miris tamjana"],
	["Aca Lukas", "Ne ljuti se krčmaru"],
	["Aca Lukas", "Pesma od bola"],
	["Aca Lukas", "Počnite bez mene"],
	["Aca Lukas", "Upali svetlo"],
	["Aca Matić", "Krčmarice još vina natoči"],
	["Aco Pejović", "Nema te nema"],
	["Adil", "Ne mogu bez tebe ja"],
	["Ado Gegaj", "Okreni moj broj"],
	["Aleksandar Dejanović", "Širok Dunav ravan Srem"],
	["Aleksandar Dejanović", "Žabaljka"],
	["Aleksandra Blagojević", "Nas dve ćerke majka ima"],
	["Amadeus bend", "100%"],
	["Amadeus bend", "Lažu te"],
	["Amadeus bend", "Nije svejedno"],
	["Ana Bekuta", "Bekrija"],
	["Ana Bekuta", "Brojanica"],
	["Ana Bekuta", "Crven konac"],
	["Ana Bekuta", "Ja nisam rođena da živim sama"],
	["Ana Bekuta", "Kralj ponoći"],
	["Ana Bekuta", "Ostavljena ja"],
	["Ana Bekuta", "Veseljak"],
	["Ana Bekuta", "Zlatiborske zore"],
	["Ana Bekuta", "Đavole"],
	["Angel Dimov", "Dva prstena, dva svedoka"],
	["Angel Dimov", "Ovo je priča o nama"],
	["Anđa Govedarović ", "I dođi lolo"],
	["Anđa Govedarović ", "Kude si pošla mori Cveto"],
	["Anđa Govedarović ", "Malo ja, malo ti"],
	["Anđa Govedarović", "Kad sam sinoć pošla iz dućana"],
	["Asim Brkan", "Jednom sam i ja volio"],
	["Asim Brkan", "Najljepšu haljinu večeras obuci"],
	["Asim Brkan", "Ne ruši mi sreću nepoznata ženo"],
	["Azemina Grbić", "Na proplanku "],
	["Baja Mali Knindža", "Ajme meni bez tebe Krajino "],
	["Baja Mali Knindža", "Ajmo brate u kafanu"],
	["Baja Mali Knindža", "Baraba sa sela"],
	["Baja Mali Knindža", "Duni vjetre malo preko jetre"],
	["Baja Mali Knindža", "Dva galeba i Verige"],
	["Baja Mali Knindža", "Ima ljudi kad popiju"],
	["Baja Mali Knindža", "Kad sam bio mali"],
	["Baja Mali Knindža", "Kum"],
	["Baja Mali Knindža", "Kćeri moje"],
	["Baja Mali Knindža", "Moj stari djedo"],
	["Baja mali knindža", "Morem plovi"],
	["Baja Mali Knindža", "Nema te krajino"],
	["Baja Mali Knindža", "Neće biti granica na Drini"],
	["Baja Mali Knindža", "Obilić me zove"],
	["Baja Mali Knindža", "Pamtim njenu kuću"],
	["Baja Mali Knindža", "Plaču nekad i bogati"],
	["Baja Mali Knindža", "Pusti Miću gadan je u piću"],
	["Baja Mali Knindža", "Rodbina"],
	["Baja Mali Knindža", "Vrati se vojvodo"],
	["Baja Mali Knindža", "Čuvaj mi se sine"],
	["Baja", "Dodir neba"],
	["Baja", "Zapisano u vremenu"],
	["Beba Selimović", "Plačem ja"],
	["Beba Selimović", "U srcu mome samo živiš ti"],
	["Beki Bekić", "Cigani su nebom prošli"],
	["Beki Bekić", "Daj mi tvoju maramu šarenu"],
	["Beki Bekić", "Dunja sa ormana"],
	["Beki Bekić", "Imam kćeri dve"],
	["Beki Bekić", "Nema više srećnih snova"],
	["Beki Bekić", "Ti ne traži sreću u meni"],
	["Beki Bekić", "Zlato Zlatija "],
	["Beki Bekić", "Zlato, Zlatija"],
	["Black Panthers", "Ja baraba a ti vila"],
	["Black Panthers", "Kakvu ženu imam"],
	["Boban Zdravković", "Ciganima srce daću"],
	["Bora Drljača", "Banja Luko"],
	["Bora Drljača", "Danijela"],
	["Bora Drljača", "Gara"],
	["Bora Drljača", "Hej jarani zora sviće"],
	["Bora Drljača", "Jovane, Jovo"],
	["Bora Drljača", "Koja gora Ivo"],
	["Bora Drljača", "Krajišnici gde ćemo na prelo"],
	["Bora Drljača", "Ne, ne, ne žalite mene"],
	["Bora Drljača", "Nema raja"],
	["Bora Drljača", "Oj Bojana pitaj Milijanu"],
	["Bora Drljača", "Oj Krajino"],
	["Bora Drljača", "Pjevaj ujko, pjevaj rode"],
	["Bora Drljača", "Plači mala, plači"],
	["Bora Drljača", "Prijo moja kako ćemo"],
	["Bora Drljača", "Sine,sine moj"],
	["Bora Drljača", "U lijepom starom gradu Višegradu"],
	["Bora Drljača", "Ćeri moje malene"],
	["Bora Spužić Kvaka", "Lepotica i sirotan"],
	["Bora Spužić Kvaka", "Pođimo u krčmu staru"],
	["Bora Spužić Kvaka", "Tajna"],
	["Boža Nikolić", "Ikona"],
	["Boža Nikolić", "Kazaljke su poklopljene"],
	["Boža Nikolić", "Lažem sebe"],
	["Boža Nikolić", "Marija, Marija"],
	["Branka Sovrlić ", "Lido, Lidija "],
	["Braća Bajić", "Šta je s tobom Radovane"],
	["Brzi", "Gataj mi ciganko"],
	["Bugarin", "Ne da te mama"],
	["Bugarin", "Teča"],
	["Bugarin", "Ćero moja ćerkice"],
	["Bugarin", "Šampionska svadba"],
	["Ciganska", "Lava manđe"],
	["Davor Badrov", "Ja baraba sve joj džaba"],
	["Dejan Marković", "Pozdrav iz Krajine"],
	["Dejan Matić", "Niko i neko"],
	["Dobrivoje Topalović", "Blago vodi što te mije"],
	["Dobrivoje Topalović", "Crno vino"],
	["Dobrivoje Topalović", "Eh da mi je"],
	["Dobrivoje Topalović", "Ne pitaj me ženo"],
	["Dobrivoje Topalović", "Tekla reka Lepenica"],
	["Dragan Kojić Keba", "Bre gidi džanum"],
	["Dragan Kojić Keba", "Imao sam"],
	["Dragan Kojić Keba", "Nemam drage, nemam druga"],
	["Dragan Kojić Keba", "Plavo oko plakalo je"],
	["Dragan Kojić Keba", "Postao sam drug samoće"],
	["Dragan Kojić Keba", "Sedam dana patim"],
	["Dragan Kojić Keba", "Stani da se pozdravimo"],
	["Dragan Đorđević Puškar", "Stari deda travu kosi"],
	["Dragan Đurić Dikula", "Nas dvojica noćas smo pijani"],
	["Dragan Đurić Dikula", "Ostavi se mene oženjena"],
	["Dragan Đurić Dikula", "Svašta, mene voli tašta"],
	["Dragana Mirković", "Kroz šljivike i livade"],
	["Dragana Mirković", "Pitaju me u mom kraju"],
	["Dragče", "Ružo rumena"],
	["Dule Rajković", "Ivana se kroz Berane šeta"],
	["Dule Rajković", "Na Kosovo da se vratim"],
	["Duško Kuliš", "Bez tebe je gorko vino"],
	["Duško Kuliš", "Suzo moja Suzana"],
	["Džej Ramadanovski ", "Od ljubavi do mržnje"],
	["Džej Ramadanovski ", "Sunce brže zađi"],
	["Džej Ramadanovski", "Dve godine duge"],
	["Džej Ramadanovski", "I Dunav laže"],
	["Džej Ramadanovski", "Imati pa nemati"],
	["Džej Ramadanovski", "Jedan, dva"],
	["Džej Ramadanovski", "Ko se s nama druži"],
	["Džej Ramadanovski", "Lubenica"],
	["Džej Ramadanovski", "Nedelja"],
	["Džej Ramadanovski", "Nijedne usne se ne ljube same"],
	["Džej Ramadanovski", "Nikom nije žao kao meni"],
	["Džej Ramadanovski", "Rađaj sinove"],
	["Džej Ramadanovski", "Sunce ljubavi"],
	["Džej Ramadanovski", "Ugasila si me"],
	["Džej Ramadanovski", "Upalite za mnom sveće"],
	["Džej Ramadanovski", "Vetrovi me lome"],
	["Džej Ramadanovski", "Zrno mudrosti"],
	["Dževad Ibrahimagić", "Rodi mi draga sina"],
	["Era Ojdanić", "Da Srbije nema"],
	["Era Ojdanić", "Domaćine živeli"],
	["Era Ojdanić", "I sve što sam steko"],
	["Era Ojdanić", "Krsna slava i tri prsta"],
	["Era Ojdanić", "Kuće male krečene u belo"],
	["Era Ojdanić", "Nedaleko od reke Rasine"],
	["Era Ojdanić", "Niko nema što Srbin imade"],
	["Era Ojdanić", "Nisam majstor da napravim bure"],
	["Era Ojdanić", "Odakle si sele"],
	["Era Ojdanić", "Oj Milice čobanice"],
	["Era Ojdanić", "Oj Srbijo tromoravko"],
	["Era Ojdanić", "Oj vojvodo Sinđeliću"],
	["Era Ojdanić", "Oženjen sam kao momak živim"],
	["Era Ojdanić", "Pauk"],
	["Era Ojdanić", "Rado bela Rado"],
	["Era Ojdanić", "Srpkinjica jedna mala"],
	["Era Ojdanić", "Srpska se truba"],
	["Era Ojdanić", "Šumadijo"],
	["Fazlija", "Evo majko sina tvoga"],
	["Ferid Avdić", "Dijana"],
	["Ferid Avdić", "Izađi mala"],
	["Goci bend", "Bi li kume kumovao"],
	["Goci bend", "Evo vozim iz Bijeljine Mana"],
	["Goci bend", "Gara"],
	["Goci bend", "Ljepotica s Pala"],
	["Goci bend", "Slavska pjesma"],
	["Goci bend", "Voli crne a volim i plave"],
	["Goci bend", "Vozi me na Pale"],
	["Gojko", "Ova kuća puna sreće"],
	["Goran Dimitrijević Dima", "Čudna žena beše Vera"],
	["Gordana Lazarević", "Svilen konac"],
	["Gordana Lazarević", "Vidovdan"],
	["Gordana Stojićević", "Ja ne mogu mila majko bez njega"],
	["Gordana Stojićević", "Pala ćuprija"],
	["Gordana Stojićević", "Pusti me da srcu nađem lek"],
	["Gordana Stojićević", "Zagrli me ti"],
	["Gvozden Radičević", "Slavica je njeno ime"],
	["Halid Bešlić", "Beograđanka"],
	["Halid Bešlić", "Dijamanti"],
	["Halid Bešlić", "Eh kad bi ti"],
	["Halid Bešlić", "Hej zoro"],
	["Halid Bešlić", "I zanesen tom ljepotom"],
	["Halid Bešlić", "Iznad Tešnja zora sviće"],
	["Halid Bešlić", "Ja bez tebe nemogu da živim"],
	["Halid Bešlić", "Lavanda"],
	["Halid Bešlić", "Miljacka"],
	["Halid Bešlić", "Mostovi tuge"],
	["Halid Bešlić", "Prokleta je žena ta"],
	["Halid Bešlić", "Prvi poljubac"],
	["Halid Bešlić", "Romanija"],
	["Halid Bešlić", "Sijede"],
	["Halid Bešlić", "Ta je žena lagala me"],
	["Halid Bešlić", "Tamburaši"],
	["Halid Bešlić", "Tebi i meni za prošle dane"],
	["Halid Bešlić", "Trebević"],
	["Halid Bešlić", "Tri ruže"],
	["Halid Bešlić", "Zlatne strune"],
	["Halid Muslimović", "Hej kafano neću više"],
	["Halid Muslimović", "Hej ljubavi u dalekom gradu"],
	["Halid Muslimović", "Mene je učilo vreme"],
	["Halid Muslimović", "Moj jarane, jarane"],
	["Halid Muslimović", "Nije mene dušo ubilo"],
	["Halid Muslimović", "Tvoje ime kao pjesma"],
	["Halid Muslimović", "Učini bar jedan pogrešan korak"],
	["Halid Muslimović", "Znam za sve sam kriv"],
	["Hanka Paldum", "Ja te pjesmom zovem"],
	["Hanka Paldum", "Volela sam oči zelene"],
	["Hanka Paldum", "Zbog tebe ostaviću sve"],
	["Haris Džinović", "Ako možeš ti"],
	["Haris Džinović", "Androverdan"],
	["Haris Džinović", "Ciganin sam ja"],
	["Haris Džinović", "Dajte vina hoću lom"],
	["Haris Džinović", "Hladno je ugrij me"],
	["Haris Džinović", "I tebe sam sit kafano"],
	["Haris Džinović", "Ja ne pijem"],
	["Haris Džinović", "Jesu l dunje procvale"],
	["Haris Džinović", "Kako mi nedostaješ"],
	["Haris Džinović", "Krčmaru vina za svirače"],
	["Haris Džinović", "Muštuluk"],
	["Haris Džinović", "Nek mi bude zadnje čaša"],
	["Haris Džinović", "Nisam ja za tebe"],
	["Haris Džinović", "Noćas mi je srce ranjeno"],
	["Haris Džinović", "O Đila"],
	["Haris Džinović", "Odlaziš od mene"],
	["Haris Džinović", "Pariške kapije"],
	["Haris Džinović", "Poznaćeš me i po mraku"],
	["Haris Džinović", "Rano je za tugu"],
	["Haris Džinović", "Sjećaš li se one noći"],
	["Haris Džinović", "Ti meni lažeš sve"],
	["Haris Džinović", "Volim te ludo znaj"],
	["Haris Džinović", "Zorice, Zoro moja"],
	["Haris Džinović", "Šta će meni više od toga"],
	["Hasan Dudić", "Crna ženo sa očima plavim"],
	["Hasan Dudić", "Došlo vreme izdaje me snaga"],
	["Hašim Kučuk Hoki", "Nazdravite drugovi"],
	["Himzo Polovina", "Čudna jada"],
	["Indira Radić", "Srpkinja je mene majka rodila"],
	["Ipče Ahmedovski", "Stari drugar, glava luda"],
	["Ismet Krcić", "Oj đevojko Milijana"],
	["Jandrino jato", "Malo Slađa, malo Zorka"],
	["Jandrino jato", "Milice ćeri"],
	["Jasmin", "Ko te prevari pa se oženi"],
	["Jasmin", "Neviđena svadba"],
	["Jašar Ahmetovski", "Jednoj ženi za sećanje dugo"],
	["Jašar Ahmetovski", "Još te volim"],
	["Jašar Ahmetovski", "Moj bagreme beli"],
	["Jašar Ahmetovski", "Sve što imam sad se ruši"],
	["Jašar Ahmetovski", "Zbog tebe sam vino pio"],
	["Jelena Broćić", "Ko ostavlja ruže"],
	["Jerina", "Svadba nabolja u selu"],
	["Jordan Nikolić ", "Cveto kalušo"],
	["Jordan Nikolić", "Ajde Jano kolo da igramo"],
	["Jordan Nikolić", "Moj golube"],
	["Jordan Nikolić", "Raslo mi je badem drvo"],
	["Jovan Perišić", "Lutalica"],
	["Jovan Perišić", "Nikada se promeniti neću"],
	["Jovan Perišić", "Sunce se rađa"],
	["Jovan Perišić", "Čovjek kafanski"],
	["Kanarinac", "Danas majko ženiš svoga sina"],
	["Kanarinac", "Svadba"],
	["Kemal Malovčić", "Ako možeš preboli"],
	["Kemal Malovčić", "Burma"],
	["Kemal Malovčić", "Cvetaju lipe"],
	["Kemal Malovčić", "Došao sam da te vidim"],
	["Kemal Malovčić", "Gori, gori srce"],
	["Kemal Malovčić", "Nena"],
	["Kemal Malovčić", "Okreće se kolo sreće"],
	["Kemal Malovčić", "Rekla si mi da ne voiš zimu"],
	["Kemal Malovčić", "Snežana"],
	["Kemal Malovčić", "Ćeri moja Aliji dal da te dam"],
	["Kemal Malovčić", "Čuvaj draga našu ćerku"],
	["Laza magistrala", "Svekrva i snajka"],
	["Legende", "Ne veruj"],
	["Lepa Brena", "Ja nemam drugi dom"],
	["Lepa Brena", "Mile voli disko"],
	["Lepa Brena", "Čik pogodi"],
	["Lepa Brena", "Šeik"],
	["Lepa Lukić", "Bisenija"],
	["Lepa Lukić", "Lepo ti je biti čobanica"],
	["Lepa Lukić", "Leti, leti bijeli golube"],
	["Lepa Lukić", "Od izvora dva putića"],
	["Lepa Lukić", "Odrasla sam ovce čuvajući"],
	["Lepa Lukić", "Oj meseče zvezdo sjajna"],
	["Lepa Lukić", "Srce je moje violina"],
	["Lepa Lukić", "U sokaku"],
	["Lepa Lukić", "Čuvam ovce kraj zelene jove"],
	["Lexington", "Dobro da nije veće zlo"],
	["Ljuba Aličić", "Crveno obuci"],
	["Ljuba Aličić", "Dva dobra druga"],
	["Ljuba Aličić", "Hoću ljubav neću prijateljstvo"],
	["Ljuba Aličić", "Jedinac sam u majke"],
	["Ljuba Aličić", "Kralj kafana"],
	["Ljuba Aličić", "Lepa Maro"],
	["Ljuba Aličić", "Neka ti kosu nose vetrovi"],
	["Ljuba Aličić", "Nekada smo ti i ja"],
	["Ljuba Aličić", "Plačite sa mnom jesenje kiše"],
	["Ljuba Aličić", "S prvom kišom"],
	["Ljuba Aličić", "Samo ona može u život da me vrati"],
	["Ljuba Aličić", "Sumorno jutro"],
	["Ljuba Aličić", "Ti ne ličiš ni na jednu"],
	["Ljuba Aličić", "U šapcu kraj Save"],
	["Ljuba Aličić", "Zbog tebe verujem"],
	["Ljuba Aličić", "Šeherezada"],
	["Ljuba Aličić", "Željana"],
	["Ljuba Kešelj", "Ja vragolan i moj deda"],
	["Ljuba Lukić", "Isprati me kaži zbogom"],
	["Ljuba Lukić", "Ja sam ostavljen"],
	["Ljuba Lukić", "Sneg je pao na orove grane"],
	["Ljubiša Stojanović Luis", "Dudo"],
	["Ljubiša Stojanović Luis", "Dunjo moja zrela"],
	["Ljubiša Stojanović Luis", "Kosa crna, oko plavo"],
	["Ljubiša Stojanović Luis", "Lele, ne idi od mene"],
	["Ljubiša Stojanović Luis", "Moj život je moje blago"],
	["Ljubiša Stojanović Luis", "Ne kuni me, ne ruži me majko"],
	["Ljubiša Stojanović Luis", "Oluja"],
	["Ljubiša Stojanović Luis", "Opa, opa"],
	["Ljubiša Stojanović Luis", "Slike u oku"],
	["Ljubiša Stojanović Luis", "Sve se osim tuge deli"],
	["Ljubiša Vasiljević", "Bjelasicom pasla stada"],
	["Ljubiša Vasiljević", "Vila Bana sa planine zvala"],
	["Ljubomir Đurović", "Dobro jutro Crna Goro"],
	["Ljubomir Đurović", "Dočekaj mi majko svate"],
	["Ljubomir Đurović", "Eh da mi je"],
	["Ljubomir Đurović", "Otišla si e pa neka"],
	["Ljubomir Đurović", "Sestra mi je poručila"],
	["Ljubomir Đurović", "Svat do svata"],
	["Ljubomir Đurović", "Tekla voda na valove"],
	["Ljubomir Đurović", "Vasojevka"],
	["Ljubomir Đurović", "Zaljubi se mlado momče"],
	["Ljubomir Đurović", "Đevere čuvaj mladu"],
	["Lutovac", "Mostovi na Morači"],
	["Maja Marijana", "Bio mi je dobar drug"],
	["Makedonska", "Aj mene majka jednu ima pa ima"],
	["Makedonska", "Ajde Jano"],
	["Makedonska", "Ako umram il zaginam"],
	["Makedonska", "Biljana platno beleše"],
	["Makedonska", "Bitola"],
	["Makedonska", "Blagujno dejče mori"],
	["Makedonska", "Bolen mi leži mlad Stojan"],
	["Makedonska", "Brala moma kapini"],
	["Makedonska", "Dejgidi ludi godini"],
	["Makedonska", "Eleno mome Eleno"],
	["Makedonska", "Eleno"],
	["Makedonska", "Jovano, Jovanke"],
	["Makedonska", "Kako što je taja čaša"],
	["Makedonska", "Laži Vere"],
	["Makedonska", "Lihnida"],
	["Makedonska", "Makedonsko devojče"],
	["Makedonska", "Mesečina"],
	["Makedonska", "Milke, dušo"],
	["Makedonska", "More sokol pie"],
	["Makedonska", "Mori Bojko, dilber devojko"],
	["Makedonska", "Na srce mi leži mila mamo"],
	["Makedonska", "Ne se fakaj done Donke"],
	["Makedonska", "Oj Vardare Makedonski"],
	["Makedonska", "Opa nina, nina naj"],
	["Makedonska", "Pileto mi pee"],
	["Makedonska", "Podigni se bre neveste"],
	["Makedonska", "Sevdalino maloj mome"],
	["Makedonska", "Site devojčinja"],
	["Makedonska", "Slušam kad šumat šumite"],
	["Makedonska", "Tuginata pusta da ostane"],
	["Makedonska", "Zajdi, zajdi"],
	["Makedonska", "Zašto si me majko rodila"],
	["Makedonska", "Šekerna"],
	["Makedonska", "Što imala ksmet Stamena"],
	["Makedonska", "Što mi e milo em drago"],
	["Manjifiko", "Pukni zoro (Montevideo)"],
	["Marina Živković", "Ajde mori dan dva"],
	["Marinko Rokvić", "Da volim drugu, ne mogu"],
	["Marinko Rokvić", "I kad me svi zaborave"],
	["Marinko Rokvić", "Jedina moja"],
	["Marinko Rokvić", "Koliba i dvor"],
	["Marinko Rokvić", "Momak veseljak"],
	["Marinko Rokvić", "Polomio vetar grane"],
	["Marinko Rokvić", "Potražiću oči nešto zelenije"],
	["Marinko Rokvić", "Skitnica"],
	["Marinko Rokvić", "Snegovi beli opet veju"],
	["Marinko Rokvić", "Svađalice moja mala"],
	["Marinko Rokvić", "Tebe nema"],
	["Marinko Rokvić", "Ti za ljubav nisi rođena"],
	["Marinko Rokvić", "Zamiriši na brazdu"],
	["Marinko Rokvić", "Zanela me svetla velikoga grada"],
	["Marko Bulat", "Eno dole u kafani"],
	["Marko Bulat", "Kad sam dečak bio"],
	["Medeni mesec", "Ivana"],
	["Medeni mesec", "Ljubi i ništa ne pitaj"],
	["Medeni mesec", "Pada kiša i hladno je"],
	["Medeni mesec", "Uz Moravu vetar duva"],
	["Medeni mesec", "Đavolica"],
	["Medenica", "Dođeš mi u san"],
	["Medenica", "Imam ljubav, al kome da je dam"],
	["Meho Puzić", "Ja ne znam gde je ona"],
	["Meho Puzić", "Kuću sam napravio,sinove poženio"],
	["Meho Puzić", "Moj brate u tuđini"],
	["Meho Puzić", "Oprosti majko molim te"],
	["Meho Puzić", "Žena prijatelja mog"],
	["Merima Njegomir", "Ivanova korita"],
	["Merima Njegomir", "Mezimica"],
	["Merima Njegomir", "Mila majko šalji me na vodu"],
	["Mećava", "Pratiću te mala do meseca"],
	["Miki Gajić", "Bole, bole ruke moje"],
	["Miki Gajić", "Dobro veče muzikanti"],
	["Miki Gajić", "Dve ćerke i sin"],
	["Mikica Antonić", "Moj behare"],
	["Milan Babić", "Ako me ostavi"],
	["Milan Babić", "Nije mi lako stari se polako"],
	["Milan Babić", "Stani, stani Ibar vodo"],
	["Milanče Radosavljević", "Anđelija"],
	["Milanče Radosavljević", "Dao bih ovo malo života"],
	["Milanče Radosavljević", "Jedna reka u mom kraju"],
	["Milanče Radosavljević", "Jedna žena plave kose"],
	["Milanče Radosavljević", "Selo moje najmilije"],
	["Milanče Radosavljević", "Sećaš li se kad smo klinci bili"],
	["Milanče Radosavljević", "Ustala je majka rano"],
	["Milanče Radosavljević", "Šoferska je tuga pregolema"],
	["Milanče Radosavljević", "Želeo bih da te zaboravim"],
	["Mile Kitić i Šemsa", "Mi se volimo"],
	["Mile Kitić", "Iz te čaše"],
	["Mile Kitić", "Kraljica trotoara"],
	["Mile Kitić", "Mala iz Novog Pazara"],
	["Mile Kitić", "Vuk samotnjak"],
	["Mile Kitić", "Šampanjac"],
	["Miligram", "Vrati mi se nesrećo"],
	["Miloš Bojanić", "Bosno moja jabuko u cvetu"],
	["Miloš Bojanić", "Hej mladosti, hej živote"],
	["Miloš Bojanić", "Samo tako, samo tako"],
	["Miloš Bojanić", "Ćeri moja mila"],
	["Miloš Bojanić", "Čigra"],
	["Mira Vasiljević", "Godine su prolazile"],
	["Mira Škorić", "Niz vene mi tiho tečeš"],
	["Mirjana Barjaktarević", "Doleteće beli golub"],
	["Mirjana Barjaktarević", "Imala sam drugaricu"],
	["Mirko Rondović", "Pljevaljski Tamburaši"],
	["Miroslav Ilić", "A selo je moje cela Šumadija"],
	["Miroslav Ilić", "Amerika"],
	["Miroslav Ilić", "Bili smo drugovi"],
	["Miroslav Ilić", "Božanstvena ženo"],
	["Miroslav Ilić", "Cele noći pijem druže"],
	["Miroslav Ilić", "Devojka iz grada"],
	["Miroslav Ilić", "Grešnica"],
	["Miroslav Ilić", "Hiljadu suza majko"],
	["Miroslav Ilić", "Jesen sedamdeset i neke"],
	["Miroslav Ilić", "Joj Rado, joj Radmila"],
	["Miroslav Ilić", "Još te nešto čini izuzetnom"],
	["Miroslav Ilić", "Lažu da vreme leči sve"],
	["Miroslav Ilić", "Luckasta si ti"],
	["Miroslav Ilić", "Moravsko predvečerje"],
	["Miroslav Ilić", "Nije život jedna žena"],
	["Miroslav Ilić", "Ova noć ima čudnu moć"],
	["Miroslav Ilić", "Polomiću čaše od kristala"],
	["Miroslav Ilić", "Pozdravi je,m pozdravi"],
	["Miroslav Ilić", "Rastanka se našeg sećam"],
	["Miroslav Ilić", "Srce moje dobro nisi stalo"],
	["Miroslav Ilić", "Tako mi nedostaješ"],
	["Miroslav Ilić", "Tebi"],
	["Miroslav Ilić", "Vino točim"],
	["Miroslav Ilić", "Zoveš me na vino"],
	["Miroslav Radovanović", "Ti si žena mog života"],
	["Mitar Mirić", "Dajte mi da živim"],
	["Mitar Mirić", "Doviđenja društvo staro"],
	["Mitar Mirić", "Duša od čoveka"],
	["Mitar Mirić", "Ja se ženim drugovi"],
	["Mitar Mirić", "Ne može nam niko ništa"],
	["Mitar Mirić", "Ne svani zoro mlada"],
	["Mitar Mirić", "Voli me danas više nego juče"],
	["Mladen Tomić", "Crveni karanfil"],
	["Nada Obrić", "Dugo te dugo očekujem"],
	["Nada Topčagić", "Jutro je"],
	["Nada Topčagić", "Mihajlo majstore"],
	["Nada Topčagić", "Treba mi rame tvoje"],
	["Narodna", "Aj veseli se kućni domaćine"],
	["Narodna", "Bosioče moj zeleni"],
	["Narodna", "Joj Rado, bela rado"],
	["Narodna", "Kralj Nikola"],
	["Narodna", "Magla padnala"],
	["Narodna", "Marš na Drinu"],
	["Narodna", "Moj Milane jabuko sa grane"],
	["Narodna", "Nesanica"],
	["Narodna", "Obraše se vinogradi"],
	["Narodna", "Oj Javore, Javore"],
	["Narodna", "Oj Jelena ćeri moja jedna"],
	["Narodna", "Oj Kosovo, Kosovo"],
	["Narodna", "Oj livado rosna travo"],
	["Narodna", "Raslo mi je badem drvo"],
	["Narodna", "Sa Ovčara i Kablara"],
	["Narodna", "Trepetljika"],
	["Narodna", "Tri livade nigde hlada nema"],
	["Narodna", "Usnila je dubok sanak"],
	["Narodna", "Zapevala sojka ptica"],
	["Narodna", "Šota"],
	["Nedeljko Bilkić", "Krčma u planini"],
	["Nedeljko Bilkić", "Neću lijeka ni ljekare"],
	["Nedeljko Bilkić", "Sedamdeset i dva dana"],
	["Nedeljko Bilkić", "Ti si sve što imam"],
	["Nedeljko Bilkić", "Veseli se srce moje"],
	["Nedžad Esadović Nećko", "Srećan ti rođendan sunce moje malo"],
	["Nedžad Salković", "Ne klepeći nanulama"],
	["Nervozni poštar", "Cirkus Kolorado"],
	["Nervozni poštar", "Nova godina"],
	["Nervozni poštar", "Ženim se"],
	["Neša Maks", "Udata je ona majko"],
	["Nikola Rokvić", "Med i slatko grožđe"],
	["Nino", "Moja si moja"],
	["Nino", "Ne voliš me više ti"],
	["Nino", "Sve si mi zabranila"],
	["Nino", "Ti si ćerko tatin sin"],
	["Nino", "Udahni duboko"],
	["Novica Negovanović", "Imam oči neposlušne"],
	["Novica Negovanović", "Kad umoran budem pao"],
	["Novica Negovanović", "Prođe leto trideseto"],
	["Novica Negovanović", "Selo moje kraj Morave"],
	["Novica Negovanović", "Ti anđeo a ja đavo"],
	["Novica Zdravković", "Splavovi"],
	["Novica Đokić", "Omile mi Jagodo"],
	["Oliver Dragojević", "A sad adio"],
	["Olivera Katarina", "Sedim u jednom pariskom lokalu"],
	["Osman Hadžić", "Ti mene ne voliš"],
	["Perica Purić", "Sve sam bitke izdržao"],
	["Predrag Gojković Cune", "Janičar"],
	["Predrag Gojković Cune", "Kafu mi draga ispeci"],
	["Predrag Gojković Cune", "Kako beše komšinice"],
	["Predrag Gojković Cune", "Ljubav mi srce mori"],
	["Predrag Gojković Cune", "Milorade bekrijo"],
	["Predrag Gojković Cune", "Moj Milane"],
	["Predrag Gojković Cune", "S one strane Morave"],
	["Predrag Gojković Cune", "Zapevajte sve one pesme stare"],
	["Predrag Gojković Cune", "Znaš li draga onu šljivu ranku"],
	["Predrag Živković Tozovac", "Aj berem grožđe"],
	["Predrag Živković Tozovac", "Ajd idemo Rado"],
	["Predrag Živković Tozovac", "Daj mi čašu rakije"],
	["Predrag Živković Tozovac", "Dano, rano pile moje malo"],
	["Predrag Živković Tozovac", "Danče"],
	["Predrag Živković Tozovac", "Dorulje"],
	["Predrag Živković Tozovac", "Dozvoli mi da te zaboravim"],
	["Predrag Živković Tozovac", "Ej čija frula"],
	["Predrag Živković Tozovac", "Ide Mile lajkovačkom prugom"],
	["Predrag Živković Tozovac", "Igrale se delije"],
	["Predrag Živković Tozovac", "Jeremija"],
	["Predrag Živković Tozovac", "Jesen prođe ja se ne oženih"],
	["Predrag Živković Tozovac", "Jesen u mom sokaku"],
	["Predrag Živković Tozovac", "Led, led, sladoled"],
	["Predrag Živković Tozovac", "Leno, Leno, Magdaleno"],
	["Predrag Živković Tozovac", "Ljubav je ljubav za sve godine"],
	["Predrag Živković Tozovac", "Malo po malo"],
	["Predrag Živković Tozovac", "Mađarica mlada"],
	["Predrag Živković Tozovac", "Mirjana"],
	["Predrag Živković Tozovac", "Na kraj sela čađava mehana"],
	["Predrag Živković Tozovac", "Of, Jano, Jano"],
	["Predrag Živković Tozovac", "Ovamo cigani"],
	["Predrag Živković Tozovac", "Oči jedne žene"],
	["Predrag Živković Tozovac", "Prazna čaša na mom stolu"],
	["Predrag Živković Tozovac", "Priča mala e pa šta"],
	["Predrag Živković Tozovac", "Rujno vino"],
	["Predrag Živković Tozovac", "Siromah sam ali volim da živim"],
	["Predrag Živković Tozovac", "Skeledžijo na Moravi"],
	["Predrag Živković Tozovac", "Suva drva odozgo"],
	["Predrag Živković Tozovac", "Ti si me čekala"],
	["Predrag Živković Tozovac", "Tražiću ljubav novu"],
	["Predrag Živković Tozovac", "U Moravu cure zagazile"],
	["Predrag Živković Tozovac", "Uzmi sve što ti život pruža"],
	["Predrag Živković Tozovac", "Violino ne sviraj"],
	["Predrag Živković Tozovac", "Vlajna"],
	["Predrag Živković Tozovac", "Vodeničarka"],
	["Predrag Živković Tozovac", "Zorice, Zorule"],
	["Predrag Živković Tozovac", "Čiča peče rakiju"],
	["Rade Jorović", "Selo moje lepše od Pariza"],
	["Rade Jorović", "Ti si žena mog života"],
	["Rade Jorović", "Žene vole oficire"],
	["Rade Petrović", "Iz tuđeg se sveta vraćam"],
	["Rade Petrović", "Kud se žuriš hej živote"],
	["Rade Petrović", "Pastirica"],
	["Rade Vučković", "Kako ću sutra bez tebe"],
	["Radiša Marković", "Neznanka"],
	["Radiša Urošević", "Ajd idemo Rado"],
	["Radiša Urošević", "Hej suzo moja"],
	["Radiša Urošević", "Morava se utišala"],
	["Radiša Urošević", "Oj moja, ružo rumena"],
	["Radiša Urošević", "Rado moja bela"],
	["Radiša Urošević", "Tecite, suze tecite"],
	["Rale Čajić", "Nisi znala da te volim"],
	["Ritam srca", "Ja hoću sad"],
	["Ritam srca", "O Sanja"],
	["Ritam srca", "Od Boga si stvorena"],
	["Rokeri s Moravu", "Čorbast pasulj volem"],
	["Roki", "Ranila me jedna žena"],
	["Rođa", "A ja imam tebe"],
	["Rođa", "Tako je suđeno"],
	["Sarievski", "Zajdi, zajdi"],
	["Sava Radusinović", "Mnogo sam te zavoleo"],
	["Savo Radović", "Žena na kapiji"],
	["Savo Radusinović", "Nemoj nikad skitnicu da ljubiš"],
	["Savo Radusinović", "Ti si žena koju ludo volim"],
	["Savo Radusinović", "Šesnaest ti leta beše"],
	["Saša Matić", "Kad ljubav zakasni"],
	["Saša Matić", "Nađi novu ljubav"],
	["Saša Matić", "Neke ptice nikad ne polete"],
	["Saša Matić", "Nije ljubav fotografija"],
	["Saša Matić", "Poklonite mi nju za rođendan"],
	["Saša Matić", "Ruzmarin"],
	["Saša Matić", "Svako ima onog kog nema"],
	["Saša Nedeljković", "Volim majko jednu ženu"],
	["Sejo Pitić", "Plava žena"],
	["Sena Ordagić", "Gubim te"],
	["Serbezovski", "Ciganin sam voljena"],
	["Serbezovski", "Osman aga"],
	["Serbezovski", "Ramo, Ramo"],
	["Serbezovski", "Rastajemo se mi"],
	["Serbezovski", "Zašto su ti kose pobele druže"],
	["Serbezovski", "Šta te briga kako živim"],
	["Sestre Aleksić", "Divlje ruže"],
	["Sevdalinka", "Ah meraka"],
	["Sevdalinka", "Ah što ćemo ljubav kriti"],
	["Sevdalinka", "Aj ja zagrizoh zeleniku jabuku"],
	["Sevdalinka", "Bere cura plav jorgovan"],
	["Sevdalinka", "Bosno moja divna mila"],
	["Sevdalinka", "Da zna zora"],
	["Sevdalinka", "Djevojka sokolu zulum učinila"],
	["Sevdalinka", "Došlo vreme izdaje me snaga"],
	["Sevdalinka", "Dvije su se vode zavadile"],
	["Sevdalinka", "Emina"],
	["Sevdalinka", "Evo ovu rumen ružu"],
	["Sevdalinka", "Harmoniko moja"],
	["Sevdalinka", "Ima jedna krčma u planini"],
	["Sevdalinka", "Jablani se povijaju"],
	["Sevdalinka", "Jutros mi je ruža procvjetala"],
	["Sevdalinka", "Kad bi znala šta mi srcu značiš"],
	["Sevdalinka", "Kad ja pođoh aman"],
	["Sevdalinka", "Kad ja pođoh na Bembašu"],
	["Sevdalinka", "Kad sretneš Hanku"],
	["Sevdalinka", "Kad umoran budem pao"],
	["Sevdalinka", "Kada moja mladost prođe"],
	["Sevdalinka", "Kraj tanana šadrvana"],
	["Sevdalinka", "Lijepi li su mostarski dućani"],
	["Sevdalinka", "Malenim sokakom"],
	["Sevdalinka", "Moj behare ko li mi te bere"],
	["Sevdalinka", "Moj dilbere"],
	["Sevdalinka", "Moj dragane što me zaboravljaš"],
	["Sevdalinka", "Moj Prijedore pun si mi sevdaha"],
	["Sevdalinka", "Moj zumbule"],
	["Sevdalinka", "Mujo kuje konja po mjesecu"],
	["Sevdalinka", "Negdje u daljini"],
	["Sevdalinka", "Neko tiho ulicom pjevuši"],
	["Sevdalinka", "Nigdje zore ni bijela dana"],
	["Sevdalinka", "Oj Safete, Sajo"],
	["Sevdalinka", "Razbolje se srce moje"],
	["Sevdalinka", "Đul Zulejha"],
	["Silvana Armenulić", "Ciganine ti što sviraš"],
	["Silvana Armenulić", "Noćas mi srce pati"],
	["Silvana Armenulić", "Rane moje"],
	["Sinan Sakić", "Delija momak"],
	["Sinan Sakić", "Ej otkad sam se rodio"],
	["Sinan Sakić", "Hvala ti za dane"],
	["Sinan Sakić", "Izađi na pet minuta"],
	["Sinan Sakić", "Lepa do bola"],
	["Sinan Sakić", "Napraviću lom"],
	["Sinan Sakić", "Nije moje srce ludo"],
	["Sinan Sakić", "Zaljubljen u tebe"],
	["Sinan Sakić", "Zoko moja Zoko"],
	["Sinan Sakić", "Čaša po čaša"],
	["Slaviša Vujić", "Ciganka mala prodaje cveće"],
	["Slavko Banjac", "Daleko negde ko zna gde"],
	["Slavko Banjac", "Ne verujem lepim ženama"],
	["Slavko Petrović", "Ženi deda unuka"],
	["Slavko Sigurnjak", "Hej krčmaru"],
	["Slobodan Mulina", "Zlatibore pitaj Taru"],
	["Slobodan Mulina", "Zlatibore pitaj Taru"],
	["Smederevac", "Imam samo 8 ari"],
	["Smederevac", "Mrak, mrak, pomračina"],
	["Smederevac", "Nas trojicu majka ima"],
	["Smederevac", "Niko nema što Srbija ima "],
	["Smederevac", "Ova naša familija"],
	["Smederevac", "Siromah sam al sam lep"],
	["Snežana Đurišić", "Lepe li su nano gružanke devojke"],
	["Snežana Đurišić", "Odakle si sele"],
	["Snežana Đurišić", "Rodila me majka"],
	["Srećko Jovović", "Devojke sa Morave"],
	["Srećko Jovović", "Vratiću se jednog dana"],
	["Srđan Milošević", "Tebi moja mazo"],
	["Staniša Stošić", "Gajtano mome mori"],
	["Staniša Stošić", "Iz banjo idem"],
	["Staniša Stošić", "Karakoco"],
	["Staniša Stošić", "Otvori mi belo Lenče"],
	["Staniša Stošić", "Simbil cveće"],
	["Staniša Stošić", "Vranjanka"],
	["Staniša Stošić", "Zapevala sojka ptica"],
	["Staniša Stošić", "Zbog tebe momo ubava"],
	["Staniša Stošić", "Šano dušo"],
	["Starogradska", "A kad tebe ljubit ne smem"],
	["Starogradska", "A sad adio"],
	["Starogradska", "Adio mare"],
	["Starogradska", "Aj po gradini"],
	["Starogradska", "Bački ručak običan"],
	["Starogradska", "Bećarac"],
	["Starogradska", "Bledi mesec"],
	["Starogradska", "Bolujem ja"],
	["Starogradska", "Cajka"],
	["Starogradska", "Cigani ljubljat pesni"],
	["Starogradska", "Ciganka sam mala"],
	["Starogradska", "Crven fesić"],
	["Starogradska", "Daj mi čašu rakije"],
	["Starogradska", "Dano rano"],
	["Starogradska", "Devojko mala"],
	["Starogradska", "Divan je kićeni Srem"],
	["Starogradska", "Donesi vina krčmarice"],
	["Starogradska", "Dunav tiho teče"],
	["Starogradska", "Dunave moje more"],
	["Starogradska", "Dva brata iz ravnog banata"],
	["Starogradska", "Evo banke cigane moj"],
	["Starogradska", "Fijaker stari"],
	["Starogradska", "Gde si da si moj golube"],
	["Starogradska", "Golubice bela"],
	["Starogradska", "Govori se da me varaš"],
	["Starogradska", "Grešnica"],
	["Starogradska", "Haljinica boje lila"],
	["Starogradska", "Hej momci mladi"],
	["Starogradska", "Hej salaši"],
	["Starogradska", "I za senkom njenom patim"],
	["Starogradska", "Izađi iz moje čaše"],
	["Starogradska", "Ja ljubim Milu"],
	["Starogradska", "Ja sam momak siroma"],
	["Starogradska", "Jedna suza na tvom licu"],
	["Starogradska", "Jesen stiže dunjo moja"],
	["Starogradska", "Jesenje lišće"],
	["Starogradska", "Kad bi ove ruže male"],
	["Starogradska", "Kad imaš druga"],
	["Starogradska", "Kad je deda lumpovao"],
	["Starogradska", "Kada padne prvi sneg"],
	["Starogradska", "Kafanski svirač"],
	["Starogradska", "Kako ću sutra bez tebe"],
	["Starogradska", "Ko te ima taj te nema"],
	["Starogradska", "Kozak"],
	["Starogradska", "Kraj jezera"],
	["Starogradska", "Krčmarice"],
	["Starogradska", "Kućerak u Sremu"],
	["Starogradska", "Ladi, ladi, lom"],
	["Starogradska", "Lažem sebe"],
	["Starogradska", "Malo ja, malo ti"],
	["Starogradska", "Moj živote šta li mi te truje"],
	["Starogradska", "Moja mala nema mane"],
	["Starogradska", "Mrkov"],
	["Starogradska", "Na kraj sela čađava mehana"],
	["Starogradska", "Ne vredi plakati"],
	["Starogradska", "Nebo je tako vedro"],
	["Starogradska", "O Jelo, Jelo, Jeleno"],
	["Starogradska", "Osam tamburaša"],
	["Starogradska", "Ostani još dan"],
	["Starogradska", "Ozo sip"],
	["Starogradska", "Pariski lokal"],
	["Starogradska", "Pijem"],
	["Starogradska", "Rastao sam pored Dunava"],
	["Starogradska", "Ravno"],
	["Starogradska", "Rekla nana"],
	["Starogradska", "Reših da se ženim"],
	["Starogradska", "Sedi Mara na kamen studencu"],
	["Starogradska", "Sejdefu majka buđaše"],
	["Starogradska", "Sonja"],
	["Starogradska", "Sremačko je selo malo"],
	["Starogradska", "Stanite dani, stanite noći"],
	["Starogradska", "Stari ciga tužne pesme svira"],
	["Starogradska", "Svilen konac"],
	["Starogradska", "Svirci moji"],
	["Starogradska", "Tamo daleko"],
	["Starogradska", "Teško je ljubit tajno"],
	["Starogradska", "Ti se nećeš vratiti"],
	["Starogradska", "Tiho teče Sava"],
	["Starogradska", "Tišina nema vlada svud"],
	["Starogradska", "Tri metera somota"],
	["Starogradska", "Višnjeve boje šal"],
	["Starogradska", "Volela sam oči zelene"],
	["Starogradska", "Volim da te volim"],
	["Starogradska", "Volim te sve više"],
	["Starogradska", "Za moju Milicu"],
	["Starogradska", "Zavejan je put za salaš moj"],
	["Starogradska", "Zbog tebe plačem"],
	["Starogradska", "Zora rudi"],
	["Starogradska", "Zračak viri kroz grančice"],
	["Starogradska", "Čamac na Tisi"],
	["Starogradska", "Čerge"],
	["Starogradska", "Čororo"],
	["Starogradska", "Škripi đeram"],
	["Starogradska", "Što se bore misli moje"],
	["Starogradska", "Žalim te momče"],
	["Starogradska", "Živim ko skitnica"],
	["Stoja Novaković", "Bela ciganka"],
	["Svetlana Ceca Ražnatović", "Kupuj majko cipelice"],
	["Tamburica 5", "Šešir moj"],
	["Toma Marinković", "Pukni zoro"],
	["Toma Zdravković", "Branka"],
	["Toma Zdravković", "Dal je moguće"],
	["Toma Zdravković", "Danka"],
	["Toma Zdravković", "Dotako sam dno života"],
	["Toma Zdravković", "Dva smo sveta različita"],
	["Toma Zdravković", "Ispod palme na obali mora"],
	["Toma Zdravković", "Jelena"],
	["Toma Zdravković", "Kafana je moja sudbina"],
	["Toma Zdravković", "Lele, lele, ciganko"],
	["Toma Zdravković", "Majci za rođendan"],
	["Toma Zdravković", "Naviko sam jana noćni život"],
	["Toma Zdravković", "O ciganko moja"],
	["Toma Zdravković", "Pesme moje"],
	["Toma Zdravković", "Plakala je"],
	["Toma Zdravković", "Poslednje pismo"],
	["Toma Zdravković", "Sanja"],
	["Toma Zdravković", "Sliku tvoju ljubim"],
	["Toma Zdravković", "Svirajte noćas samo za nju"],
	["Toma Zdravković", "Tamburaši, tamburaši"],
	["Toma Zdravković", "Tužno leto"],
	["Toma Zdravković", "Umoran sam od života"],
	["Tomislav Čolović", "Majka Muju šišala na struju"],
	["Tomislav Čolović", "Mali mrav"],
	["Tropiko bend", "Bojim se"],
	["Tropiko bend", "Paranoja"],
	["Usnija Redžepova", "Aj ruse kose curo imaš"],
	["Usnija Redžepova", "Kazuj krčmo džerimo"],
	["Usnija Redžepova", "Niška Banja"],
	["Vasilija Radojčić", "Dimitrijo sine Mitre"],
	["Vasilija Radojčić", "Mito bekrijo"],
	["Vasilija Radojčić", "Na Uskrs sam se rodila"],
	["Vera Matović", "Hajde, hajde milovanje moje"],
	["Vera Matović", "Marko, Marko sunce moje žarko"],
	["Vesna Zmijanac i Merlin", "Jorgovani"],
	["Vesna Zmijanac", "Kazni me kazni"],
	["Vesna Zmijanac", "Kunem ti se životom"],
	["Vesna Zmijanac", "Ne kunite crne oči"],
	["Vesna Zmijanac", "Nevera moja"],
	["Vida Pavlović", "Daj mi majko drugi život"],
	["Vida Pavlović", "Misli mi čitaš"],
	["Vida Pavlović", "Niko nije kao majka"],
	["Vida Pavlović", "Ostala je pesma moja"],
	["Vida Pavlović", "Sanak me mori"],
	["Vida Pavlović", "Svadben venac kapiju mi krasi"],
	["Vida Pavlović", "Svako traži novu ljubav"],
	["Vida Pavlović", "Sve je prošlo među nama"],
	["Zaim Imamović", "Kraj tanana šadrvana"],
	["Zlata Petrović", "Dođi da mi ruke greješ"],
	["Zlatko Pejaković", "Čerge"],
	["Zoran Gajić", "Nisam te se nagledao"],
	["Zoran Janković Zoka", "Šta ću ti ja"],
	["Zoran Jovanović", "Kapetan potonulog broda"],
	["Zoran Jovanović", "Ruža i baštovan"],
	["Zoran Jovanović", "Svadba (Visok bagrem)"],
	["Zoran Jovanović", "Zapalio bih celo selo"],
	["Zoran Kalezić", "Dobro veče izgubljena nado"],
	["Zoran Kalezić", "Eh da sam malo mlađi"],
	["Zoran Kalezić", "Još ne sviće rujna zora"],
	["Zoran Kalezić", "Moj dobri anđele"],
	["Zoran Kalezić", "Pivljanka"],
	["Zoran Kalezić", "Pod Javorom selo što je"],
	["Zoran Kalezić", "Sestra mi je poručila"],
	["Zoran Kalezić", "Tamo gde ognjišta dime"],
	["Zorica Brunclik", "Avlije, avlije"],
	["Zorica Brunclik", "Božić"],
	["Zorica Brunclik", "Ja znam"],
	["Zorica Brunclik", "Lažem sebe"],
	["Zorica Brunclik", "Moja zakletvo"],
	["Zorica Brunclik", "Otkopčano jeleče"],
	["Zorica Brunclik", "Đurđevdan"],
	["Zvonko Bogdan ", "Iz Vršca stiže glas"],
	["Zvonko Bogdan ", "Jedan stari kontrabas"],
	["Zvonko Bogdan ", "Kad mi pišeš mila mati"],
	["Zvonko Bogdan ", "Kad sam bio mlađan lovac ja"],
	["Zvonko Bogdan ", "Kad sam bio vojnik u tom Somboru"],
	["Zvonko Bogdan ", "Kad te vidim na sokaku"],
	["Zvonko Bogdan ", "Kafana Spartak"],
	["Zvonko Bogdan ", "Ova naša livada"],
	["Zvonko Bogdan ", "Pargar na pargar"],
	["Zvonko Bogdan ", "Sedi Mara na kamen studencu"],
	["Zvonko Bogdan ", "Ta tvoja suknja plava"],
	["Zvonko Bogdan ", "Te oči tvoje zelene"],
	["Zvonko Bogdan ", "Temerav"],
	["Zvonko Bogdan ", "U tvom oku"],
	["Zvonko Bogdan ", "Varala me jedna cura mala"],
	["Zvonko Bogdan ", "Zlatan prsten"],
	["Zvonko Bogdan ", "Čuješ seko"],
	["Zvonko Bogdan", "Do dva konja a obadva vrana"],
	["Zvonko Bogdan", "Mrkov"],
	["Zvonko Bogdan", "Sagradiću šajku"],
	["Zvonko Bogdan", "Seoska sam lola"],
	["Ćana", "Kućo moja stara"],
	["Ćana", "Sve je moje tamo"],
	["Čeda Marković", "I da se vrate godine mlade"],
	["Čeda Marković", "Svirete mi čalgii"],
	["Čeda Marković", "Žal iz mladosti"],
	["Ćira", "Fenomenalno"],
	["Đani", "Ja stalno pijem "],
	["Đani", "Još te sanjam"],
	["Šaban Bajramović", "Ej, opa, cupa"],
	["Šaban Bajramović", "Maruška"],
	["Šaban Bajramović", "Parno gras"],
	["Šaban Bajramović", "Prokleta je Amerika"],
	["Šaban Bajramović", "Sećaš li se hanuma"],
	["Šaban Bajramović", "Čšaje šukarije"],
	["Šaban Bajramović", "Đelem, đelem"],
	["Šaban Šaulić i Gorica Ilić", "Ti si greh za moju dušu"],
	["Šaban Šaulić", "Bio sam pijanac"],
	["Šaban Šaulić", "Bojana"],
	["Šaban Šaulić", "Bojana"],
	["Šaban Šaulić", "Dajte mi utjehu"],
	["Šaban Šaulić", "Donesi Kato"],
	["Šaban Šaulić", "Dva galeba bela"],
	["Šaban Šaulić", "Golubica"],
	["Šaban Šaulić", "Gordana"],
	["Šaban Šaulić", "Hajde srećo moja"],
	["Šaban Šaulić", "Hoćemo li u Šabac na vašar"],
	["Šaban Šaulić", "Kraljica srca mog"],
	["Šaban Šaulić", "Kume brate"],
	["Šaban Šaulić", "Lančić mali"],
	["Šaban Šaulić", "Najlepša ženo"],
	["Šaban Šaulić", "Ne pitaj me druže moj"],
	["Šaban Šaulić", "Ne plači dobri domaćine"],
	["Šaban Šaulić", "Ne plači dušo"],
	["Šaban Šaulić", "Nemoj pogled da skrivaš"],
	["Šaban Šaulić", "Pozno bih te međ hiljadu žena"],
	["Šaban Šaulić", "Pruži ruku pomirenja"],
	["Šaban Šaulić", "S namerom dođoh u veliki grad"],
	["Šaban Šaulić", "Sam za stolom jedan čovek sedi"],
	["Šaban Šaulić", "Skini prsten s desne ruke"],
	["Šaban Šaulić", "Sneg je opet Snežana"],
	["Šaban Šaulić", "Snošti"],
	["Šaban Šaulić", "Stamena"],
	["Šaban Šaulić", "Svadbarska pesma"],
	["Šaban Šaulić", "Uvenuće narcis beli"],
	["Šaban Šaulić", "Verujem u ljubav"],
	["Šaban Šaulić", "Viđaš li mi staru ljubav"],
	["Šaban Šaulić", "Čaše lomim"],
	["Šaban Šaulić", "Šadrvani"],
	["Šaban Šaulić", "Žal"],
	["Šako Polumenta", "Daj mi malo vremena"],
	["Šeki Turković", "Da su meni 22"],
	["Šeki Turković", "Dotaknuću"],
	["Šeki Turković", "Hoću malo rodnog neba"],
	["Šeki Turković", "Poslednji boem"],
	["Šeki Turković", "Spomenar"],
	["Šerif Konjević", "Imaš li malo ljubavi za mene"],
	["Šerif Konjević", "Pitao sam prolaznike"],
	["Šerif Konjević", "Zbog tebe sam vino pio"],
	["Šerif Konjović", "Još te volim i patim"],
	["Željko Samardžić", "Kafanska pevačica"],
	["Željko Samardžić", "Sipajte još jedan Whisky"],
	["Željko Šašić", "Ima dana i kafana"],
	["Šaban Šaulić", "Svrati reče čovek"],
	["Zorica Brunclik", "Ne daj da nas rastave"],
	["Hasan Dudić", "Sad je kasno za novi početak"],
	["Slobodan Lalić", "Alaj volim kad je pomelena"],
	["Ljuba Kešelj", "Čiji su ono sirotani"],
	["Željko Šašić", "Mali je ovo grad"]

];

var zabavne = [
	["Apsolutno romantično","Đoletova pesma"],
	["Arsen Dedić","Zagrli me"],
	["Bajaga", "Dobro jutro džezeri"],
	["Bajaga", "Moji su drugovi"],
	["Bajaga", "Muzika na struju"],
	["Balašević", "Al se nekad dobro jelo"],
	["Balašević", "Baby blue"],
	["Balašević", "Devojka sa čardaš nogama"],
	["Balašević", "D-mol"],
	["Balašević", "Jesen stiže dunjo moja"],
	["Balašević", "Pesma o jednom petlu"],
	["Balašević", "Priča o Vasi Ladačkom"],
	["Balašević", "Ringišpil"],
	["Balašević", "Slovenska"],
	["Bebek", "Laku noć svirači"],
	["Bebek", "Oprosti mi što te volim"],
	["Bebek", "Sinoć sam pola kafane popio"],
	["Bebek", "Žuta ruža s Dunava"],
	["Bijelo Dugme", "Hajdemo u planine"],
	["Bijelo Dugme", "Hop cup poskočiću"],
	["Bijelo Dugme", "Lipe cvatu"],
	["Bijelo Dugme", "Napile se ulice"],
	["Bijelo Dugme", "Ne spavaj mala moja"],
	["Bijelo Dugme", "Ružica si bila"],
	["Bijelo Dugme", "Tako ti je mala moja"],
	["Boba Stefanović", "Obriši suze draga"],
	["Crni Biseri", "Ruže su crvene"],
	["Dado Topić", "Princeza"],
	["Danijel Popović","Džuli"],
	["Divlje Jagode", "Motori"],
	["Dragan Stojnić", "Bila je tako lijepa"],
	["Dragan Stojnić", "Maestro i violina"],
	["Dubrovački Trubaduri", "Dok palme njišu grane"],
	["Duško Jakšić", "Somborske ruže"],
	["Duško Jakšić", "Sve moje jeseni su tužne"],
	["Duško Jakšić", "Čamac na Tisi"],
	["Dženan Lončarević", "Ludujem"],
	["Hari i Maja Šuput", "Sedamnaest ti je godina"],
	["Hari Mata Hari", "Lejla"],
	["Hari Mata Hari", "Prsten i zlatni lanac"],
	["Indeksi", "Bacila je sve niz rijeku"],
	["Indeksi", "Sve ove godine"],
	["Indeksi", "Žute dunje"],
	["Indexi","Ti si mi bila u svemu naj"],
	["Ivica Šerfezi", "Suze liju plave oči"],
	["Ivo Robić", "Jabuke i trešnje"],
	["Ivo Robić", "Samo jednom se ljubi"],
	["Jasna Zlokić", "Skitnica"],
	["Kemal Monteno", "Jedne noći u decembru"],
	["Kićo Slabinac", "Plavuša"],
	["Kićo Slabinac", "Zbog jedne divne crne žene"],
	["Lado Leskovar", "U predgrađu"],
	["Leo Martin", "Odiseja"],
	["Miki Jevremović", "Ako jednom vidiš Mariju"],
	["Miki Jevremović", "Grkinja"],
	["Miki Jevremović", "Kad bih znao da je sama"],
	["Miki Jevremović", "Pijem"],
	["Miki Jevremović", "S kim si sada kad je tužno vreme"],
	["Mišo Kovač", "Jedan dan života"],
	["Mišo Kovač", "Ostala si uvijek ista"],
	["Mišo Kovač","Proplakaće zora"],
	["Nena Ivošević", "Kaži zašto me ostavi"],
	["Nena Ivošević", "Piši mi"],
	["Nervozni poštar", "Cirkus Kolorado"],
	["Nervozni poštar", "Nova godina"],
	["Novi Fosili", "Milena generacijo"],
	["Novi Fosili", "Za dobra stara vremena"],
	["Oliver Dragojević", "Cesarica"],
	["Oliver Dragojević", "Jesen stiže dunjo moja"],
	["Oliver Dragojević", "Magdalena"],
	["Oliver Dragojević", "Nedostaješ mi ti"],
	["Oliver Dragojević", "Oprosti mi pape"],
	["Oliver Dragojević", "Vjeruj u ljubav"],
	["Oliver Dragojević", "Što to biješe ljubav"],
	["Oliver Mandić", "Pomagajte drugovi"],
	["Petar Grašo","Utorak"],
	["Plavi orkestar", "Ako su to samo bile laži"],
	["Plavi orkestar", "Bolje biti pijan nego star"],
	["Pro-Arte","Jedna mala plava"],
	["Riblja Čorba", "Dobro jutro"],
	["Riblja Čorba", "Dva dinara druže"],
	["Riblja Čorba", "Kad sam bio mlad"],
	["Riblja Čorba", "Kada padne noć"],
	["Riblja Čorba", "Nemoj da ideš mojom ulicom"],
	["Riblja Čorba", "Ostani đubre do kraja"],
	["S.A.R.S.", "Lutka"],
	["Sedmorica Mladih", "Mala tema iz srema"],
	["Sedmorica Mladih", "Mansarda mali stan"],
	["Zabranjeno pušenje", "Vukota"],
	["Zabranjeno pušenje", "Zenica bluz"],
	["Zdravko Čolić", "April u Beogradu"],
	["Zdravko Čolić", "Emili"],
	["Zdravko Čolić", "Glavo luda"],
	["Zdravko Čolić", "Jedina"],
	["Zdravko Čolić", "Krasiva"],
	["Zdravko Čolić", "Kristina"],
	["Zdravko Čolić", "Mađarica"],
	["Zdravko Čolić", "Merak"],
	["Zdravko Čolić", "Pisaću joj pisma duga"],
	["Zdravko Čolić", "Pjevam danju, pjevam noću"],
	["Zdravko Čolić", "Podlugovi"],
	["Zdravko Čolić", "Produži dalje"],
	["Zdravko Čolić", "Pusti, pusti modu"],
	["Zdravko Čolić", "Ružice, Ružo, Ruška"],
	["Zdravko Čolić", "Ti si mi u krvi"],
	["Zdravko Čolić", "Živiš u oblacima mala"],
	["Zlatko Pejaković", "Ove noći"],
	["Čobi", "Dolina našeg detinjstva"],
	["Čobi", "Lola"],
	["Đorđe Marjanović", "Zvižduk u osam"],
	["Đuza Stoiljković", "Devojko mala"],
	["Željko Joksimović", "Lane moje"],
	["Željko Joksimović", "Ljubavi"],
	["Željko Joksimović", "Nije ljubav stvar"],
	["Željko Joksimović","Leđa o leđa"],
	["Boba Stefanović", "Kažu mi da još si uvek sama"],
	["Riblja Čorba", "Zelena trava doma mog"],
	["Željko Samardžić","Ljubavnik"]
];

var internacionalne = [
    ["Adriano Celentano", "Soli"],
    ["Al Martino", "Blue spanish eyes"],
	["Andy Williams", "Love story"],
	["Andy Williams", "Speak softly love"],
	["Antonio Banderas", "El Mariachi"],
	["Beatles", "Let it be"],
	["Beatles", "Yesterday"],
	["Chubby Checker", "Let's twist again"],
	["Charles Aznavour", "She"],
	["Dean Martin", "Sway"],
	["Elvis Presley", "It’s now or never"],
	["Elvis Presley", "Love me tender"],
	["Engelbert Humperdinck", "Please, release me"],
	["Engelbert Humperdinck", "Quando, quando, quando"],
	["Engelbert Humperdinck", "The last waltz"],
	["Fats Domino", "Blueberry Hill"],
	["Frankie Laine", "My little one"],
	["Frankie Sinatra", "My way"],
	["Frank Sinatra", "New York, New York"],
	["Frank Sinatra", "Happy birthday"],
	["Frank Sinatra", "Strangers in the night"],
	["Gilbert Bécaud", "Nathalie"],
	["Grčka", "Aponi zoi"],
	["Grčka", "Deca Pireja"],
	["Grčka", "Maria meta kitrina"],
	["Grčka", "Mi Mou Thimonis Matia Mou"],
	["Grčka", "Fragosiriani"],
	["Grčka", "Xronia doksasmena"],
	["Grčka", "Kyra Giorgena"],
	["Grčka", "Lohias"],
	["Grčka", "Oči pune suza"],
	["Grčka", "O Stratis"],
	["Grčka", "An imoun plousios"],
	["Grčka", "Siko horepse sirtaki"],
	["Grčka", "Strose to stroma"],
	["Grčka", "Zugla"],
	["Hugo Iglesias", "Besamo mucho"],
	["Izraelska", "Hava Nagila"],
	["Los Lobos", "La Bamba"],
	["Louis Armstrong", "Saints"],
	["Louis Armstrong", "Wonderful world"],
	["Louis Prima", "Buona sera signorina"],
	["Louis Prima", "Just a gigolo"],
	["Luciano Pavarotti", "Torna a Sorento"],
	["Mambo kings", "Beautiful Maria"],
	["Nat king Cole", "Fascination"],
	["Nat king Cole", "Quizas"],
	["Morris Albert", "Feelings"],
	["Ray Charles", "Crying time"],
	["Rocco Granata", "Marina"],
	["Ruska", "Tamna je noć"],
	["Ruska", "Rjabinuška"],
	["Ruska", "Podmoskovske večeri"],
	["Ruska", "Kaljinka"],
	["The Platters", "Only you"],
	["Toto Cutugno", "L Italiano"],
	["Tom Jones", "Green, green grass"],
	["Ruska", "Dve gitare"],
	["Ruska", "Androverdan"],
	["Ruska", "Cigani ljubljat pesnji"],
	["Ruska", "Kalinka"],
	["Ruska", "Katjuša"],
	["Ruska", "Kozak"],
	["Ruska", "Maruška"],
	["Ruska", "O đila"],
	["Ruska", "Oči čornie"],
	["Ruska", "Podmoskovske večeri"],
	["Ruska", "Rjabinuška"],
	["Kris Kristofferson", "Help Me Make It Through the Night"],
	["Chuck Berry", "Johnny B. Goode"],
	["Julio Iglesias", "Historia de un amor"],
	["Ruska", "Tamna je noć"]
];

var zenske = [
    ["Aleksandra Radović", "Još danas"],
    ["Aleksandra Radović", "Kao so u moru"],
    ["Aleksandra Radović", "Postala sam jaka"],
    ["Aleksandra Radović", "Bivši dragi"],
    ["Aleksandra Radović", "Jesam te pustila"],
    ["Aleksandra Radović", "Još danas"],
    ["Aleksandra Radović", "Ko so u moru"],
    ["Aleksandra Radović", "Postala sam jaka"],
    ["Ambasadori", "Dođi u 5 do 5"],
    ["Ana Bekuta", "Bekrija"],
    ["Ana Bekuta", "Brojanica"],
    ["Ana Bekuta", "Crven konac"],
    ["Ana Bekuta", "Dobro jutro lepi moj"],
    ["Ana Bekuta", "Đavole"],
    ["Ana Bekuta", "Imam jedan život"],
    ["Ana Bekuta", "Ja nisam rođena"],
    ["Ana Bekuta", "Kralj ponoći"],
    ["Ana Bekuta", "Oluja"],
    ["Ana Bekuta", "Uspomene"],
    ["Ana Bekuta", "Veseljak"],
    ["Ana Bekuta", "Zlatiborske zore"],
    ["Ana Nikolić", "Baksuz"],
    ["Ana Nikolić", "Januar"],
    ["Ana Nikolić", "Mišo moj"],
    ["Ana Nikolić", "Romale, Romali"],
    ["Bebek-Zana", "Jabuke i vino"],
    ["Bekvalac", "Gubim tlo pod nogama"],
    ["Bekvalac", "Hajde"],
    ["Bekvalac", "Kraj mene imaš sve"],
    ["Bekvalac", "Ako poludim u 25"],
    ["Bekvalac", "Neću da se zaljubim"],
    ["Bekvalac", "Poker za dvoje"],
    ["Bekvalac", "Sve je to ljubav"],
    ["Bekvalac", "Mali signali"],
    ["Bekvalac", "Navika"],
    ["Bekvalac", "Nije za mene"],
    ["Bekvalac", "Nikotin"],
    ["Bekvalac", "Ponovo"],
    ["Nataša Kojić", "A gde si ti"],
    ["Nataša Kojić", "Višnja u čokoladi"],
    ["Božinovska", "Neodoljivo"],
    ["Brena", "Čačak"],
    ["Brena", "Čačak"],
    ["Brena", "Četri godine"],
    ["Brena", "Čik pogodi"],
    ["Brena", "Čik pogodi-rumba"],
    ["Brena", "Čuvala me mama"],
    ["Brena", "Dama iz Londona"],
    ["Brena", "Disko urnebes"],
    ["Brena", "Duge noge"],
    ["Brena", "Golube"],
    ["Brena", "Grad"],
    ["Brena", "Hajde da se volimo"],
    ["Brena", "Ja nemam drugi dom"],
    ["Brena", "Jedan dan života"],
    ["Brena", "Luda za tobom"],
    ["Brena", "Miki, Mićo"],
    ["Brena", "Mile voli disko"],
    ["Brena", "Okrećeš mi leđa"],
    ["Brena", "Pariski lokal"],
    ["Brena", "Robinja"],
    ["Brena", "Šeki"],
    ["Brena", "Ti si moj greh"],
    ["Brunclik", "A tebe nema"],
    ["Brunclik", "Avlije, avlije"],
    ["Brunclik", "Dan po dan"],
    ["Brunclik", "Košava"],
    ["Brunclik", "Moja zakletvo"],
    ["Brunclik", "Muke moje"],
    ["Brunclik", "Ne daj da nas rastave"],
    ["Brunclik", "Otkopčano jeleče"],
    ["Brunclik", "Što se mala uobrazi"],
    ["Brunclik-Šaban", "Kako ti je kako živiš"],
    ["Ceca", "1000 razloga"],
    ["Ceca", "39.2"],
    ["Ceca", "Ako te ona odbije"],
    ["Ceca", "Batali"],
    ["Ceca", "Beograd"],
    ["Ceca", "Bruka"],
    ["Ceca", "Brže"],
    ["Ceca", "Crveno"],
    ["Ceca", "Decenija"],
    ["Ceca", "Devojko, veštice"],
    ["Ceca", "Doktor"],
    ["Ceca", "Dragane moj"],
    ["Ceca", "Drugarice, prokletnice sa vokalima"],
    ["Ceca", "Drugarice, prokletnice"],
    ["Ceca", "Gore od ljubavi"],
    ["Ceca", "Idi dok si mlad"],
    ["Ceca", "Ime i prezime"],
    ["Ceca", "Isuse"],
    ["Ceca", "Kad bi bio ranjen"],
    ["Ceca", "Kažem da te volim"],
    ["Ceca", "Kukavica"],
    ["Ceca", "Lepi grome moj"],
    ["Ceca", "Lepotan"],
    ["Ceca", "Manta"],
    ["Ceca", "Monotonija"],
    ["Ceca", "Mrtvo more"],
    ["Ceca", "Nagovori"],
    ["Ceca", "Neću da budem ko mašina"],
    ["Ceca", "Nemoj mi prići"],
    ["Ceca", "Neodoljiv, neumoljiv"],
    ["Ceca", "Nevaljala"],
    ["Ceca", "Oproštajna večera"],
    ["Ceca", "Pazi s kime spavaš"],
    ["Ceca", "Pile"],
    ["Ceca", "Ponuđen o počašćen"],
    ["Ceca", "Popij me kao lek"],
    ["Ceca", "Poziv"],
    ["Ceca", "Pustite me da ga vidim"],
    ["Ceca", "Rekom bez vode"],
    ["Ceca", "Šta je to utvojim venama"],
    ["Ceca", "To Miki"],
    ["Ceca", "Tražio si sve"],
    ["Ceca", "Trula višnja"],
    ["Ceca", "U tvojoj majici"],
    ["Ceca", "Vazduh koji dišem"],
    ["Ceca", "Volela sam volela"],
    ["Ceca", "Votka sa utehom"],
    ["Ceca", "Zaboravi"],
    ["Ceca", "Zabraniću srcu da te voli"],
    ["Ceca", "Zabranjeni grad"],
    ["Ceca", "Znam"],
    ["Ćukteraš", "Ekskluziva"],
    ["Ćukteraš", "Hteo to"],
    ["Ćukteraš", "Ja te samo podsećam na nju"],
    ["Ćukteraš", "Metar"],
    ["Ćukteraš", "Život mi oduzmi"],
    ["Ćukteraš", "Manastir"],
    ["Ćukteraš", "Manija"],
    ["Ćukteraš", "Metar"],
    ["Ćukteraš", "Monaliza"],
    ["Ćukteraš", "Mrgude"],
    ["Ćukteraš", "Nema pravila"],
    ["Ćukteraš", "Prevari me"],
    ["Ćukteraš", "Ružo bela"],
    ["Ćukteraš", "Votka"],
    ["Ćukteraš", "Zvaćeš je mojim imenom"],
    ["Danijela-Kemo", "Ovako ne mogu dalje"],
    ["Dara Bubamara", "Dobro jutro nikome"],
    ["Dara Bubamara", "Dodirni me"],
    ["Dara Bubamara", "Dunav"],
    ["Dara Bubamara", "Galama"],
    ["Dara Bubamara", "Ja neću da ga vidim"],
    ["Dara Bubamara", "Javite mi javite"],
    ["Dara Bubamara", "Mami, mami"],
    ["Dara Bubamara", "Ne recite mi"],
    ["Dara Bubamara", "Niti me ljubiš"],
    ["Dara Bubamara", "Polje jagoda"],
    ["Dara Bubamara", "Svi su tu kao nekada"],
    ["Danijela i Kemo", "Ovako ne mogu dalje"],
    ["Dragana", "Jeleni košute ljube"],
    ["Dragana", "Još si meni drag"],
    ["Dragana", "Kada te ugledam"],
    ["Dragana", "Kaži mi sunce moje"],
    ["Dragana", "Kroz šljivike"],
    ["Dragana", "Luče moje"],
    ["Dragana", "Milo moje štote nema"],
    ["Dragana", "Ne veruj im srećo"],
    ["Dragana", "Nisam ni metar od tebe"],
    ["Dragana", "O da li znaš"],
    ["Dragana", "Pitaju me u mom kraju"],
    ["Dragana", "Plači zemljo"],
    ["Dragana", "Poslednje veče"],
    ["Dragana", "Ruže svetaju samo u pesmama"],
    ["Dragana", "Simpatija"],
    ["Dragana", "Slađano moje slađano"],
    ["Dragana", "Spasi me samoće"],
    ["Dragana", "Sto ću čuda učiniti"],
    ["Dragana", "Umirem majko"],
    ["Elma", "Gradske priče"],
    ["Esma Redžepova", "Opa nina, nina"],
    ["Goca Lazarević", "Vidovdan"],
    ["Goca Stojićević", "Zagrli me ti"],
    ["Goca Stojićević", "Godine su prolazile"],
    ["Goca Stojićević", "Ja ne mogu milamajko"],
    ["Goca Tržan", "Bumerang"],
    ["Goca Tržan", "Haljina"],
    ["Hanka Paldum", "Crne kose"],
    ["Hanka Paldum", "Ja te pjesmom zovem"],
    ["Hanka Paldum", "Voljela sam, voljela"],
    ["Ivana Banfić-Merlin", "Godinama"],
    ["Ivana Selakov", "Moje je ime sreća"],
    ["Jadranka Stojaković", "Moj dragi stoj, stoj"],
    ["Jasna Zlokić", "Samo simpatija"],
    ["Jelena Broćić", "Ko ostavlja ruže"],
    ["Jelena Broćić", "Od života jače"],
    ["Jelena Kostov", "Nisam bila spremna"],
    ["Jelena Marinkov", "Slika"],
    ["Josipa Lisac", "Magla"],
    ["Jelena Rozga", "Bižuterija"],
    ["Jelena Tomašević", "Jutro"],
    ["Jelena Tomašević", "Med i žaoka"],
    ["Jelena Tomašević", "Okeani"],
    ["Jelena Tomašević", "Oro moje"],
    ["Josipa Lisac", "Magla"],
    ["Leontina", "Crno pa se ne vidi"],
    ["Leontina", "Kad prave ljubavi ginu"],
    ["Lepa Lukić", "Srce je moje violina"],
    ["Magazin", "Ako poludim"],
    ["Magazin", "Briga me"],
    ["Magazin", "Brodolom"],
    ["Magazin", "Da je slađe zaspati"],
    ["Magazin", "Da li znaš da te ne volim"],
    ["Magazin", "Dani su bez broja"],
    ["Magazin", "Ginem"],
    ["Magazin", "Gutljaj vina"],
    ["Magazin", "Ide mi"],
    ["Magazin", "Kad bi bio blizu"],
    ["Magazin", "Kasno je"],
    ["Magazin", "Ko me zove"],
    ["Magazin", "Minus i plus"],
    ["Magazin", "Minut srca tvog"],
    ["Magazin", "Ne bi ti oprostila"],
    ["Magazin", "Oko moje sanjivo"],
    ["Magazin", "Opijum"],
    ["Magazin", "Ostani njezin do kraja"],
    ["Magazin", "Piši mi"],
    ["Magazin", "Prorok"],
    ["Magazin", "Rano"],
    ["Magazin", "S druge strane mjeseca"],
    ["Magazin", "Što je to"],
    ["Magazin", "Suze biserne"],
    ["Magazin", "Tek iz navike"],
    ["Magazin", "Ti si mi sve"],
    ["Magazin", "Ti si želja mog života"],
    ["Magazin", "Ti sam ti zime"],
    ["Magazin", "U ponoć pozvoni"],
    ["Maja Blagdan", "Gitara Dalmatina"],
    ["Maja Blagdan", "Ljubavi moja jedina"],
    ["Maja Blagdan", "Rajski cvite moj"],
    ["Maja Blagdan", "Sedam suza"],
    ["Maja Blagdan", "Sveta ljubav"],
    ["Maja Blagdan", "Ti si čovjek moj"],
    ["Maja Marijana", "Bio mi je dobar drug"],
    ["Maja Marijana", "Crni panter"],
    ["Maja Marijana", "Napraviću lom"],
    ["Maja Marijana", "Ona dobro zna"],
    ["Maja Marković", "Nije nam se dalo"],
    ["Maja Nikolić", "Uzmi me"],
    ["Maja Nikolić", "Varali me svi"],
    ["Maja Odžaklijevska", "Sve ti opraštam"],
    ["Maja Odžaklijevska", "Ti si taj što luduje"],
    ["Maja Šuput", "Nije mi važno"],
    ["Maja Šuput i Hari", "17 mi je godina"],
    ["Marina Perazić", "Kolačići"],
    ["Marina Perazić", "Lažljiva"],
    ["Marina Živković", "Dan dva"],
    ["Marina Živković", "Pet godina voljena"],
    ["Marina Živković", "Zavet ljubavi"],
    ["Marta Savić", "Brojiš mi, brojiš"],
    ["Marta Savić", "Da li to ljubav"],
    ["Marta Savić", "Delo i nedelo"],
    ["Marta Savić", "Duj, duj"],
    ["Marta Savić", "Erotika"],
    ["Marta Savić", "Nisi tu"],
    ["Marta Savić", "Nova godina"],
    ["Marta Savić", "Papuče"],
    ["Marta Savić", "Samoodbrana"],
    ["Marta Savić", "Vernost je prevara"],
    ["Marta Savić", "Zbogom je suvišno"],
    ["Meri Cetinić", "U predgrađu"],
    ["Meri Cetinić & Tedi", "Konobo moja"],
    ["Meri Cetinić", "Simpatija"],
    ["Merima", "Mezimica"],
    ["Merima", "Ivanova Korita"],
    ["Mica Demirović", "Seti me se jednog dana"],
    ["Milica Todorović", "Laka"],
    ["Milica Todorović", "Reci ja sam"],
    ["Milica Todorović", "Sa bilo kim"],
    ["Milica Todorović", "SMS"],
    ["Milica Todorović", "Tri čaše"],
    ["Milica Todorović", "Uporedi me"],
    ["Milica Todorović", "Zašto cura sedi sama"],
    ["Milijana Ralević Mana", "Čekam te u nedelju"],
    ["Mina", "Česma"],
    ["Mina & Zana", "Da li me vara sa tobom"],
    ["Mina", "Ljubav"],
    ["Mina", "Muziku pojačaj"],
    ["Mina", "Puče istina"],
    ["Mina", "Sexi robot"],
    ["Mina", "Zar da verujem u mir"],
    ["Mina", "Isti igrači"],
    ["Mina", "Još jedna u nizu"],
    ["Minea", "Lastavica"],
    ["Minea", "Mimo zakona"],
    ["Minea", "Rano"],
    ["Minea", "Što bi mi"],
    ["Minea", "U ponoć pozvoni mi"],
    ["Mira Škorić", "Ista nam je tuga"],
    ["Mira Škorić", "Najbolji prijatelji"],
    ["Mira Škorić", "Otkači"],
    ["Mira Škorić", "Rodiću ti sina"],
    ["Mira Škorić", "Tako si pao"],
    ["Mira Škorić", "Manastirska vrata"],
    ["Mira Barjaktarević", "Imala sam drugaricu"],
    ["Mira Barjaktarević", "Ja nemogu mila majko bez njega"],
    ["Mira Vasiljević", "Godine su prolazile"],
    ["Nada Topčagić", "Izvini dušo, izvini"],
    ["Nada Topčagić", "Jutro je"],
    ["Nada Topčagić", "Mihajlo"],
    ["Neda Ukraden", "Da se nađemo na pola puta"],
    ["Neda Ukraden", "Zora je"],
    ["Neda Ukraden", "Evo sviće"],
    ["Neda Ukraden", "Gdje god bio"],
    ["Neda Ukraden", "Ne da tebe tvoja Neda"],
    ["Negativ", "Ja bih te sanjala"],
    ["Negativ", "Ti mene ne voliš"],
    ["Nena Đurović", "Pred očima mojim"],
    ["Nena Đurović", "U redu"],
    ["Nina Badrić", "Ako kažeš da me ne voliš"],
    ["Nina Badrić", "Ako odeš ti"],
    ["Nina Badrić", "Budi tu"],
    ["Nina Badrić", "Čarobno jutro"],
    ["Nina Badrić", "Godinama"],
    ["Nina Badrić", "I na kraj svijeta"],
    ["Nina Badrić", "I am so excited"],
    ["Nina Badrić", "Za ljubav neću moliti"],
    ["Nina Badrić", "Ko odeš ti"],
    ["Nina Badrić", "Ne ostavljaj me"],
    ["Nina Badrić", "Nije mi svedjedno"],
    ["Nina Badrić", "Što učinio si ti"],
    ["Nina Badrić & Emilija", "Vlak"],
    ["Novi Fosili", "Dajmi minutu"],
    ["Novi Fosili", "Iz navike"],
    ["Novi Fosili", "Ja sam za ples"],
    ["Novi Fosili", "Košulja plava"],
    ["Novi Fosili", "Milena generacijo"],
    ["Novi Fosili", "Pričaš mi o ljubavi"],
    ["Novi Fosili", "Za dobra stara vremena"],
    ["Rada Manojlović", "10 ispod nule"],
    ["Rada Manojlović", "Bole usne neverne"],
    ["Rada Manojlović", "Bolje ona nego ja"],
    ["Rada Manojlović", "Nikada više"],
    ["Rada Manojlović", "Rođendan"],
    ["Riva", "Ja sam za ples"],
    ["Romana", "Brišem suze"],
    ["Romana", "Ček bez pokrića"],
    ["Romana", "Eh kad bih s tobom bila"],
    ["Romana", "Ja noćas umirem"],
    ["Romana", "Kad mi gore obrazi"],
    ["Romana", "Lažem"],
    ["Romana", "Mene ti"],
    ["Romana", "Ovjeren"],
    ["Romana", "Prava žena"],
    ["Romana", "Samoodbrana"],
    ["Romana", "Ti ipak svojoj djeci"],
    ["Romana", "Venera"],
    ["Romana & Šašić", "Prođi, priđi"],
    ["Sanja Đorđević", "Bole mlade godine"],
    ["Sanja Đorđević", "Crveni lak"],
    ["Sanja Đorđević", "Na mojoj strani kreveta"],
    ["Sanja Đorđević", "Od tuge overena"],
    ["Sanja Đorđević", "Poruči pesmu"],
    ["Sanja Đorđević", "Točkovi"],
    ["Sanja Đorđević", "Za inat rođena"],
    ["Sanja Maletić", "S vremena na vreme"],
    ["Sanja Stojanović", "Kažu da sam luda"],
    ["Sanja Stojanović", "Varaš me"],
    ["Seka Aleksić", "Ale, ale"],
    ["Seka Aleksić", "Aspirin"],
    ["Seka Aleksić", "Balkan"],
    ["Seka Aleksić", "Bezobrazna"],
    ["Seka Aleksić", "Boli stara ljubav"],
    ["Seka Aleksić", "Crno i zlatno"],
    ["Seka Aleksić", "Da sam muško"],
    ["Seka Aleksić", "Dođi i uzme me"],
    ["Seka Aleksić", "Idi lepi moj"],
    ["Seka Aleksić", "Iskoristi moje mane"],
    ["Seka Aleksić", "Jedna više"],
    ["Seka Aleksić", "Kad čujem korak tvoj"],
    ["Seka Aleksić", "Kap parfema"],
    ["Seka Aleksić", "Ko da sutra"],
    ["Seka Aleksić", "Kraljice"],
    ["Seka Aleksić", "Majstor za žene"],
    ["Seka Aleksić", "Moje prvo bio si neverstvo"],
    ["Seka Aleksić", "Ne gledaj me kao da me nema"],
    ["Seka Aleksić", "Oči plave boje"],
    ["Seka Aleksić", "Spremna sam na sve"],
    ["Seka Aleksić", "Sviđa mi se tvoja devojka"],
    ["Seka Aleksić", "U kafani punoj dima"],
    ["Seka Aleksić", "Za ljubav mobilna"],
    ["Seka Aleksić", "Poslednji let"],
    ["Selma Bajrami", "Ostrvo tuge"],
    ["Severina", "Ajde zlato moje"],
    ["Severina", "Ante"],
    ["Severina", "Bojate bane buški"],
    ["Severina", "Bože moj"],
    ["Severina", "Bred Pit"],
    ["Severina", "Daj da biram"],
    ["Severina", "Daj mi daj"],
    ["Severina", "Djevojka sa sela"],
    ["Severina", "Dodirni mi koljena"],
    ["Severina", "Esmeralda"],
    ["Severina", "Gas, gas"],
    ["Severina", "Idi"],
    ["Severina", "Italijana"],
    ["Severina", "Ja samo pjevam"],
    ["Severina", "Kad si sam"],
    ["Severina", "Krivi spoj"],
    ["Severina", "Mala je dala"],
    ["Severina", "Mili moj"],
    ["Severina", "Milost"],
    ["Severina", "Moja stvar"],
    ["Severina", "Od rođendana do rođendana"],
    ["Severina", "Paloma nera"],
    ["Severina", "Pogled ispod obrva"],
    ["Severina", "Prijateljice"],
    ["Severina", "Savršena žena"],
    ["Severina", "Štikla"],
    ["Severina", "Tako je to"],
    ["Severina", "Tarapana"],
    ["Severina", "Trava zelena"],
    ["Severina", "Tvoja prva djevojka"],
    ["Severina", "Vatra i led"],
    ["Severina", "Virujen u te"],
    ["Severina", "Voli me, ne voli"],
    ["Severina & Boris", "Tko je kriv"],
    ["Severina & Žera", "Ti si srce moje"],
    ["Silvana", "Ciganine ti što sviraš"],
    ["Silvana", "Nad izvorom"],
    ["Silvana", "Noćas mi srce pati"],
    ["Silvana", "Rane moje"],
    ["Silvija Nedeljković", "Hani, hani"],
    ["Slađana Đorđević Bucka", "Kazni me"],
    ["Snežana Đurišić", "A kleo se kleo"],
    ["Snežana Đurišić", "Boli, boli sve me boli"],
    ["Snežana Đurišić", "Budi muško"],
    ["Snežana Đurišić", "Da zaigram, da zapevam"],
    ["Snežana Đurišić", "Imena mi mog"],
    ["Snežana Đurišić", "Isplači se, otvori dušu"],
    ["Snežana Đurišić", "Jedna suza na mom licu"],
    ["Snežana Đurišić", "Kad bi još jednom pokušali"],
    ["Snežana Đurišić", "Kandilo"],
    ["Snežana Đurišić", "Kiše"],
    ["Snežana Đurišić", "Kuće male"],
    ["Snežana Đurišić", "Lepi moj"],
    ["Snežana Đurišić", "Posteljo, bela posteljo"],
    ["Snežana Đurišić", "Pričaj mi pričaj"],
    ["Snežana Đurišić", "Srna"],
    ["Snežana Đurišić", "Sve je prošlo među nama"],
    ["Snežana Savić", "Tri poljupca"],
    ["Stoja", "Dijamanti"],
    ["Stoja", "Moj život jemoje blago"],
    ["Stoja", "Nešto mi govori"],
    ["Stoja", "Starija"],
    ["Stoja", "Živeo"],
    ["Šemsa", "Bol do ludila"],
    ["Šemsa", "Dokle da se kradom sastajemo"],
    ["Šemsa", "Južni ritam"],
    ["Šemsa", "Kako da ti pomognem"],
    ["Šemsa", "Mi se volimo"],
    ["Šemsa", "Ne verujem nikom više"],
    ["Šemsa", "Ne, ne, ne"],
    ["Šemsa", "Pristajem na sve"],
    ["Šemsa", "Prođi sa mnom ispod"],
    ["Šemsa", "Volele se oči crne"],
    ["Šerifović", "Bol do ludila"],
    ["Šerifović", "Molitva"],
    ["Šerifović", "Ne dam bolu da me slomi"],
    ["Tajči", "Hajde da ludujemo"],
    ["Tajči", "Moj mali je opasan"],
    ["Tajči & Hari", "17 ti je godina"],
    ["Tamara Todeska", "1003"],
    ["Tanja Savić", "Gde ljubav putuje"],
    ["Tanja Savić", "Igračka"],
    ["Tanja Savić", "Incident"],
    ["Tanja Savić", "Kameleon"],
    ["Tanja Savić", "Kao brodovi"],
    ["Tanja Savić", "Minut ljubavi"],
    ["Tanja Savić", "Nova Godina"],
    ["Tanja Savić", "Poludela"],
    ["Tanja Savić", "Zlatnik"],
    ["Tanja Savić", "Za moje dobro"],
    ["Tanja Savić", "Zašto me uobraz ljubiš"],
    ["Tap 011", "Lujka"],
    ["Tereza Kesovija", "Ke sera sera"],
    ["Tifa-Elvira", "Baraba"],
    ["Tijana Dapčević", "Jača od sudbine"],
    ["Tijana Dapčević", "Kao da"],
    ["Tijana Dapčević", "Ne daj"],
    ["Tijana Dapčević", "Negativ"],
    ["Tijana Dapčević", "Ona to zna"],
    ["Tijana Dapčević", "Rođen da budeš moj"],
    ["Tijana Dapčević", "Stepski vuk"],
    ["Tijana Dapčević", "Sve je isto samonjega nema"],
    ["Tijana Dapčević", "Zemlja mojih snova"],
    ["Tina Ivanović", "Bunda od nerca"],
    ["Tina Ivanović", "Kabrio porše"],
    ["Tina Ivanović", "Zaljubljena"],
    ["Usnija", "Kazuj krčmo džerimo"],
    ["Vanesa Šokčić", "Čudan čovek"],
    ["Vanna", "Crazy"],
    ["Vanna & Gibonni", "Ja ću budan sanjati"],
    ["Vasilija", "Mito Bekrijo"],
    ["Vanna", "Crazy"],
    ["Verica Pandilovska", "Kučkin sin"],
    ["Vesna Zmijanac", "Da budemo zajedno"],
    ["Vesna Zmijanac", "Godina je prošla"],
    ["Vesna Zmijanac", "Jorgovani"],
    ["Vesna Zmijanac", "Kazni me kazni"],
    ["Vesna Zmijanac", "Kraj nogu ti mrem"],
    ["Vesna Zmijanac", "Kunem ti se životom"],
    ["Vesna Zmijanac", "Ne kunite crne oči"],
    ["Vesna Zmijanac", "Nevera"],
    ["Vesna Zmijanac-Merlin", "Jorgovani"],
    ["Vesna Pisarović", "Da sutra umrem"],
    ["Vesna Pisarović", "Da znaš"],
    ["Vesna Pisarović", "Ja čekam noć"],
    ["Vesna Pisarović", "Kad bi bila tvoja voljena"],
    ["Vesna Pisarović", "Za tebe stvorena"],
    ["Vesna Pisarović", "Bježi od mene"],
    ["Vida", "Daj mi majko drugi život"],
    ["Vida", "Ostala je pesma moja"],
    ["Viki", "Bajadera"],
    ["Viki", "Da li si dobro spavao"],
    ["Viki", "Ti muškarac"],
    ["Viki", "Crno na belo"],
    ["Viki", "Godine"],
    ["Viki", "Mahinalno"],
    ["Viki", "Mariš li"],
    ["Viki", "Obeležena"],
    ["Viktorija", "Arija"],
    ["Viktorija", "Barakuda"],
    ["Viktorija", "Daj, ne pitaj"],
    ["Vlatka Pokos", "Metak"],
    ["Xenia", "Troje"],
    ["Zana", "Dodirni mi kolena"],
    ["Zana", "Jabuke i vino"],
    ["Zana", "Majstor za poljupce"],
    ["Zana", "Mladiću moj"],
    ["Zana", "Što ne znam gde si sad"],
    ["Zlata Petrović", "Dođi da mi ruke greješ"],
    ["Zlata Petrović", "Mirišeš na nju"],
    ["Zlata Petrović", "Plači,moli"],
    ["Zlata Petrović", "Zagušljivo"],
    ["Zorana", "Sanjam te još"],
    ["Zorana", "Za ljubav stvorena"],
    ["Zorica Andrijašević", "Mali reno"],
    ["Zorica Marković", "Mirno spavaj nano"]

];

$(document).ready(function () {
    $('#narodne').DataTable({
        data: narodne,
        columns: [
            {
                title: "Izvođač"
            },
            {
                title: "Naziv"
            }
        ],
        language: {
            processing: "",
            search: "Pretraga:",
            lengthMenu: "Prikaži _MENU_ zapisa",
            info: "Prikazano od _START_ do _END_ od ukupno _TOTAL_ zapisa",
            infoEmpty: "",
            infoFiltered: "",
            infoPostFix: "",
            loadingRecords: "",
            zeroRecords: "Ne postoji traženi izvođač ili pesma!!!",
            emptyTable: "",
            paginate: {
                first: "Prva",
                previous: "Prethodna",
                next: "Sledeća",
                last: "Poslednja"
            },
            aria: {
                sortAscending: ": poređajte uzlazno",
                sortDescending: ": poređajte silazno"
            }
        }
    });
});

$(document).ready(function () {
    $('#zabavne').DataTable({
        data: zabavne,
        columns: [
            {
                title: "Izvođač"
            },
            {
                title: "Naziv"
            }
        ],
        language: {
            processing: "",
            search: "Pretraga:",
            lengthMenu: "Prikaži _MENU_ zapisa",
            info: "Prikazano od _START_ do _END_ od ukupno _TOTAL_ zapisa",
            infoEmpty: "",
            infoFiltered: "",
            infoPostFix: "",
            loadingRecords: "",
            zeroRecords: "Ne postoji traženi izvođač ili pesma!!!",
            emptyTable: "",
            paginate: {
                first: "Prva",
                previous: "Prethodna",
                next: "Sledeća",
                last: "Poslednja"
            },
            aria: {
                sortAscending: ": poređajte uzlazno",
                sortDescending: ": poređajte silazno"
            }
        }
    });
});

$(document).ready(function () {
    $('#internacionalne').DataTable({
        data: internacionalne,
        columns: [
            {
                title: "Izvođač"
            },
            {
                title: "Naziv"
            }
        ],
        language: {
            processing: "",
            search: "Pretraga:",
            lengthMenu: "Prikaži _MENU_ zapisa",
            info: "Prikazano od _START_ do _END_ od ukupno _TOTAL_ zapisa",
            infoEmpty: "",
            infoFiltered: "",
            infoPostFix: "",
            loadingRecords: "",
            zeroRecords: "Ne postoji traženi izvođač ili pesma!!!",
            emptyTable: "",
            paginate: {
                first: "Prva",
                previous: "Prethodna",
                next: "Sledeća",
                last: "Poslednja"
            },
            aria: {
                sortAscending: ": poređajte uzlazno",
                sortDescending: ": poređajte silazno"
            }
        }
    });
});

$(document).ready(function () {
    $('#zenske').DataTable({
        data: zenske,
        columns: [
            {
                title: "Izvođač"
            },
            {
                title: "Naziv"
            }
        ],
        language: {
            processing: "",
            search: "Pretraga:",
            lengthMenu: "Prikaži _MENU_ zapisa",
            info: "Prikazano od _START_ do _END_ od ukupno _TOTAL_ zapisa",
            infoEmpty: "",
            infoFiltered: "",
            infoPostFix: "",
            loadingRecords: "",
            zeroRecords: "Ne postoji traženi izvođač ili pesma!!!",
            emptyTable: "",
            paginate: {
                first: "Prva",
                previous: "Prethodna",
                next: "Sledeća",
                last: "Poslednja"
            },
            aria: {
                sortAscending: ": poređajte uzlazno",
                sortDescending: ": poređajte silazno"
            }
        }
    });
});

/*lokalizacija na srpski*/
//$('#zabavne').DataTable({
//    language: {
//        processing: "Traitement en cours...",
//        search: "Pretraga:",
//        lengthMenu: "Afficher _MENU_ &eacute;l&eacute;ments",
//        info: "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
//        infoEmpty: "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
//        infoFiltered: "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
//        infoPostFix: "",
//        loadingRecords: "Chargement en cours...",
//        zeroRecords: "Aucun &eacute;l&eacute;ment &agrave; afficher",
//        emptyTable: "Aucune donnée disponible dans le tableau",
//        paginate: {
//            first: "Prva",
//            previous: "Prethodna",
//            next: "Sledeća",
//            last: "Poslednja"
//        },
//        aria: {
//            sortAscending: ": poređajte uzlazno",
//            sortDescending: ": poređajte silazno"
//        }
//    }
//});
